name: Merge any release branch to uat
on:
  pull_request:
    types: [closed]

env:
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: echo Branch Name
        run: echo "${{ env.BRANCH_NAME }} "