name: Epic Branch Sync
on:
  pull_request:
    types: [closed]

# only populated on pull_request events
#  SOURCE_BRANCH: ${{ github.head_ref }} 
#  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
   epic-branch-sync:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # after execution, two env variables should be set, MERGE_SUCCESS & MERGE_FAILURE
      - name: epic branch sync
        uses:  bholland-bh/merge-branch@master
        with:
          type: now
          target_branch: ^epic/.*
          github_token: ${{ github.token }}
          message: automerge from ${{ github.base_ref }}

      - name: step_two
        id: step_two
        run: echo "$MERGE_FAILURE"

      - name: step_three
        id: step_three
        run: echo ${{ env.MERGE_FAILURE }}
      
      # - name: Notify slack failure
      #   if: failure()
      #   env:
      #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      #   uses: voxmedia/github-action-slack-notify-build@v1
      #   with:
      #     channel_id: C02HLKYAU56 # blue-devs
      #     status: $MERGE_FAILURE
      #     color: danger

