name: Epic Branch Sync
on:
  pull_request:
    types: [closed]

# only populated on pull_request events
#  SOURCE_BRANCH: ${{ github.head_ref }} 
#  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
   epic-branch-sync:
    if: github.event.pull_request.merged == true && github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: sync epic/test w/ develop
        uses:  bholland-bh/merge-branch@master
        with:
          type: now
          target_branch: ^epic/.*
          github_token: ${{ github.token }}
          message: automerge from ${{ github.base_ref }}