name: Epic Branch Sync
on:
  pull_request:
    types: [closed]

name: Epic Branch Sync
on:
  pull_request:
    types: [closed]

jobs:
   epic-branch-sync:
    uses: bholland-bh/blue-action-workflows/.github/workflows/target_regex_sync.yml@main
    with:
      source_branch: main
    secrets:
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}