on: push
jobs:
  jira-check-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Script
        uses: ./.github/actions/jira-check-action
