name: Merge release down to develop
on:
  pull_request:
    types: [closed]

jobs:
   automerge-release-to-main:
    uses: bholland-bh/blue-action-workflows/automerge_release_down_to_target_branch.yml@main
    with:
      target_branch: main
    secrets:
      SLACK_NOTIFICATIONS_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}