name: Merge release down to develop
on:
  pull_request:
    types: [closed]

jobs:
   automerge-release-to-main:
    uses: bholland-bh/blue-action-workflows/.github/workflows/automerge_release_down_to_target_branch.yml@main