name: Merge any release branch to uat
on:
  pull_request:
    types: [closed]

env:
  SOURCE_BRANCH: ${{ github.head_ref }} # only populated on pull_request events
  TARGET_BRANCH: ${{ github.base_ref }} # only populated on pull_request events

jobs:
   merge-branch:
    if: github.event.pull_request.merged == true && startsWith(${{ env.TARGET_BRANCH }}, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> develop
        uses: devmasx/merge-branch@master
        with:
          target_branch: main
          github_token: ${{ github.token }}
        env:
          INPUT_MESSAGE: 'automerge from ${{ env.BRANCH_NAME }}'