name: Merge release changes back into develop
on:
  pull_request:
    types: [closed]

# only populated on pull_request events
#  SOURCE_BRANCH: ${{ github.head_ref }} 
#  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
   merge-to-develop:
    if: github.event.pull_request.merged == true && startsWith(github.base_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: merge release changes down to develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
          message: automerge from ${{ github.head_ref }}