name: Merge any release branch to uat
on:
  pull_request:
    types: [closed]

# only populated on pull_request events
#  SOURCE_BRANCH: ${{ github.head_ref }} 
#  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
   merge-branch:
    if: github.event.pull_request.merged == true && startsWith(github.base_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge release -> develop
        uses: devmasx/merge-branch@master
        with:
          target_branch: main
          github_token: ${{ github.token }}
        env:
          INPUT_MESSAGE: 'automerge from ${{ github.head_ref }}'