name: Merge release down to develop
on:
  push:
    branches:
      - main

      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          channel_id: C02HLKYAU56 # blue-devs
          status: test slack message
          color: danger