name: Test Slack Message
on:
  push:
    branches:
      - main

jobs:
   message-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: C02HLKYAU56 # blue-devs
          status: test slack message
          color: danger
